# --- Configuração do Servidor ---
server:
  port: ${SERVER_PORT:8080}

cloudflare:
  r2:
    endpoint: https://9cdcbd46f7ba87af9983bd5f006fad56.r2.cloudflarestorage.com
    region: auto
    access-key: 41962b375fb89bd3005309d0ad9ceada
    secret-key: ed7ec917cb0359c72987a34fc9c06eca359079f7435e74ec7d20b1f00853e655
    bucket: sara-emprega-pdf

spring:
  application:
    name: sara-emprega
  util:
    encoderStrength: 4

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:sara_emprega}?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      continue-on-error: true

  cloud:
    consul:
        enabled: false

    service-registry:
      auto-registration:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  public-key: ${JWT_PUBLIC_KEY_CONTENT}
  private-key: ${JWT_PRIVATE_KEY_CONTENT}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.datasource: DEBUG

youtube:
  api:
    key: AIzaSyA4KNeM3jYrDEIWT78-9NU42QmfgG8-UZM
    url: https://www.googleapis.com/youtube/v3/videos
