server:
  port: 8080

spring:
  util:
    encoderStrength: 10

  datasource:
    url: jdbc:mysql://localhost:3306/sara_emprega
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: administrador
    password: admin123

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  public-key: ${JWT_PUBLIC_KEY_PATH}
  private-key: ${JWT_PRIVATE_KEY_PATH}
