spring.application.name=saraEmprega
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.cloud.consul.enabled=false

spring.cloud.consul.host=host.docker.internal
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
