server:
  port: 8080

cloudflare:
  r2:
    endpoint: https://9cdcbd46f7ba87af9983bd5f006fad56.r2.cloudflarestorage.com
    region: auto
    access-key: 41962b375fb89bd3005309d0ad9ceada
    secret-key: ed7ec917cb0359c72987a34fc9c06eca359079f7435e74ec7d20b1f00853e655
    bucket: sara-emprega-pdf

spring:
  util:
    encoderStrength: 4

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update   # cria as tabelas a cada inicialização
    show-sql: true
    defer-datasource-initialization: true  # garante que o Hibernate cria antes do data.sql
    properties:
      hibernate.enable_lazy_load_no_trans: true

  sql:
    init:
      mode: always        # executa SEMPRE o data.sql
      continue-on-error: true  # ignora pequenos erros caso algo já exista

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  public-key: classpath:jwtKeys/public_key.pem
  private-key: classpath:jwtKeys/private_key.pem

youtube:
  api:
    key: AIzaSyA4KNeM3jYrDEIWT78-9NU42QmfgG8-UZM
    url: https://www.googleapis.com/youtube/v3/videos